# How to install Numpy - Deafult available in python, if not use pip

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip show numpy

Name: numpy
Version: 1.20.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /home/pratiksha/anaconda3/lib/python3.8/site-packages
Requires: 
Required-by: tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


# How to Create an array -
1. Generate Array using np.array()

    Ordered collection of elements of basic data types of given length
    Syntax: numpy.array(object)




In [2]:
import numpy as np

In [17]:
arr1=np.array([10,20,30,40])
print(arr1)
#type means type of the arr1 variable
print(type(arr1))
#dtype means data type of element
print(arr1.dtype)
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))

[10 20 30 40]
<class 'numpy.ndarray'>
int64
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [16]:
arr1=np.array([2,3,4,'x',"string element"])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(type(arr1[0]))
print(type(arr1[1]))
print(type(arr1[2]))
print(type(arr1[3]))
print(type(arr1[4]))

['2' '3' '4' 'x' 'string element']
<class 'numpy.ndarray'>
<U21
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [136]:
# Max-Min
import numpy

# creating a numpy array of integers
arr=np.array([1,2,4,50,0])
print(np.max(arr))
print(np.min(arr))

50
0


# 2. Generate Array using linespace

    numpy.linspace()- returns equally spaced numbers within the given range based on the sample number
    Syntax:numpy.linspace(start,stop,num)
    start - start of interval range
    stop - end of interval range
    num - number of samples to be generated



In [23]:
arr2=np.linspace(1,50,5)
print(arr2)
arr3=np.linspace(0,90,6,retstep=True)
print(arr3)

[ 1.   13.25 25.5  37.75 50.  ]
(array([ 0., 18., 36., 54., 72., 90.]), 18.0)


# 3. Generate arrays using arange( )

    numpy.arange()- returns equally spaced numbers with in the given range based on step size
    Syntax:numpy.arange(start,stop,step)
    start - start of interval range
    stop - end of interval range
    step - step size of interval



In [28]:
arr4=np.arange(10) #start
print("arr4:",arr4)
arr5=np.arange(10,20) #start ,stop
print("arr5:",arr5)
arr6=np.arange(10,30,2) #start ,stop,step
print("arr6:",arr6)

arr4: [0 1 2 3 4 5 6 7 8 9]
arr5: [10 11 12 13 14 15 16 17 18 19]
arr6: [10 12 14 16 18 20 22 24 26 28]


In [29]:
arr7=np.arange(start=30,stop=10,step=-2)
print(arr7)

[30 28 26 24 22 20 18 16 14 12]


# 4. Generate arrays using ones

    numpy.ones()- returns an array of given shape and type filled with ones
    Syntax:numpy.ones(shape,dtype)
    shape - integer or sequence of integers
    dtype - data type (default:float)



In [34]:
arr8=np.ones((3,3))
print(arr8)
print()
arr9=np.ones((4,4),int)
print(arr9)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# 5. Generate arrays using zeros

    numpy.zeros()- returns an array of given shape and type filled with zeros
    Syntax:numpy.zeros(shape,dtype)
    shape - integer or sequence of integers
    dtype - data type (default:float)



In [35]:
arr10=np.zeros((3,3))
print(arr10)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 6. Generate arrays using random.rand( )

    numpy.random.rand()- returns an array of given shape filled with random values
    Syntax:numpy.random.rand(shape)
    shape - integer or sequence of integers



In [38]:
arr11=np.random.rand(5)
print("arr11:",arr11)
arr12=np.random.rand(5,6) # five rows and six colunms
print("\narr12:",arr12)

arr11: [0.29927591 0.51390264 0.06844478 0.96583311 0.05552097]

arr12: [[0.52215902 0.35141319 0.58893087 0.64421543 0.23079915 0.30169175]
 [0.88343997 0.57828523 0.65958282 0.63617071 0.18670949 0.86813955]
 [0.82402567 0.78531638 0.70766125 0.94283505 0.04663066 0.80909486]
 [0.53019123 0.64063915 0.33764483 0.43454074 0.278462   0.54035633]
 [0.31707322 0.75658719 0.31791003 0.99011008 0.02132412 0.60155035]]


Select 5 random integers from the range of 1 to 100

In [40]:
arr13=np.random.randint(1,100,(5,3))
print(arr13)

[[26  7 35]
 [71 30 88]
 [63 66 34]
 [25 24 15]
 [83 25 63]]


In [42]:
arr13.shape

(5, 3)

# Operations on Array
1. Check Shape of Array


In [44]:
a=np.array([[4,5,6],[6,8,9]])
print(a)
print("\n",a.shape)

[[4 5 6]
 [6 8 9]]

 (2, 3)


# 2. Reshaping Size of Array

    reshape()- recasts an array to new shape without changing it’s data



In [45]:
b=a.reshape(3,2)
print(b)

[[4 5]
 [6 6]
 [8 9]]


In [47]:
c=np.arange(50,70).reshape(5,4)
print(c)

[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]
 [62 63 64 65]
 [66 67 68 69]]


In [55]:
d=c.reshape(4,5)
print(d)

[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


# 3. Accessing Elements

In [59]:
# print 53 in c array
print(c[0][3])
#print 62 in d array
print(d[2][2])

53
62


In [66]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,5,1]])
print(a)
print()
#print second and third rows
print(a[1:3])
print()
#print first and second colunms
print(a[:,(0,1)])

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 5 1]]

[[4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]
 [0 5]]


In [73]:
# make subset of (0,0),(0,1),(1,0),(1,1) elements
a_sub=a[0:2,0:2]
print(a_sub)

[[1 2]
 [4 5]]


Replace 5 to 55 in subset and check it is modifying in original array or not?

In [74]:
a_sub[1,1]=55
print(a_sub)

[[ 1  2]
 [ 4 55]]


In [75]:
print(a)

[[ 1  2  3]
 [ 4 55  6]
 [ 7  8  9]
 [ 0  5  1]]




    Note - Original array gets modified if you update subset elements



# 4. Numpy Addition

In [76]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
print(a.sum())
print(np.sum(a))
print(np.sum(a,axis=None))

45
45
45


In [84]:
#Colunm Element addition
print(np.sum(a,axis=0))
#Row Element addition
print(np.sum(a,axis=1))

[12 15 18]
[ 6 15 24]


In [88]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
c=np.sum(a+b)
d=np.add(a,b)
print(a)
print()
print(b)
print()
print(c)
print()
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

495

[[11 22 33]
 [44 55 66]
 [77 88 99]]


# 5. Numpy Subtract

In [89]:
print(np.subtract(a,b))

[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


# 6. Numpy Multiplication


In [90]:
print(np.multiply(a,b))

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


# 7. Numpy Division

In [91]:
print(np.divide(b,a))

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


# 8. Numpy Remainder

In [92]:
print(np.remainder(b,a))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 9. Numpy Transpose

In [93]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [96]:
print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 10. Numpy Append

In [98]:
print(a)
print()
print(np.append(a,[[0,4,7]],axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 4 7]]


In [99]:
print(b)
# To append in rows, transpose horizontal array to vertical array
c=np.array([[13,14,15]])
c=np.transpose(c)
print(c)
d=np.append(b,c,axis=1) #Elements are added in rows
print(d)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[13]
 [14]
 [15]]
[[10 20 30 13]
 [40 50 60 14]
 [70 80 90 15]]


# 11. Numpy Insert

In [102]:
a=np.array([[2,4,8],[3,5,7]])
print(a)
print()
a_insert=np.insert(a,1,[[9,1,0]],axis=0)
print(a_insert)

[[2 4 8]
 [3 5 7]]

[[2 4 8]
 [9 1 0]
 [3 5 7]]


In [104]:
print(a_insert)
print()
a_delete=np.delete(a_insert,1,axis=0)
print(a_delete)

[[2 4 8]
 [9 1 0]
 [3 5 7]]

[[2 4 8]
 [3 5 7]]


# Matrices

    Rectangular arrangement of numbers in rows and columns
    Rows run horizontally and columns run vertically

Create a matrix

    matrix()- returns a matrix from an array type object or string of data
    Syntax:numpy.matrix(data)



In [105]:
m1=np.matrix("4,5,6;4,7,9;6,0,1")
print(m1)

[[4 5 6]
 [4 7 9]
 [6 0 1]]


In [106]:
m1.shape

(3, 3)

In [107]:
m1.size

9

In [114]:
print(m1[1,1]) # Accessing Elements

7


In [115]:
subset=m1[0:2,0:2]
print(subset)

[[4 5]
 [4 7]]


In [117]:
# Updating Values
subset[1,1]=55
print(subset)
print()
print(m1)

[[ 4  5]
 [ 4 55]]

[[ 4  5  6]
 [ 4 55  9]
 [ 6  0  1]]


# Matrix Addition

    numpy.add(matrix_1,matrix_2)



In [118]:
m1

matrix([[ 4,  5,  6],
        [ 4, 55,  9],
        [ 6,  0,  1]])

In [119]:
m2=np.matrix("1,2,3;4,5,6;7,8,9")
m2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [121]:
add_matrix=np.add(m1,m2)
add_matrix

matrix([[ 5,  7,  9],
        [ 8, 60, 15],
        [13,  8, 10]])

# Subtraction

    numpy.subtract(m1,m2)



In [123]:
sub_matrix=np.subtract(m1,m2)
sub_matrix

matrix([[ 3,  3,  3],
        [ 0, 50,  3],
        [-1, -8, -8]])

# Multiplication

    numpy.dot(matrix_1,matrix_2)



In [125]:
# Matrix multiplication rules should be followed
print(m1)
print(m2)
multi=np.dot(m1,m2)
multi

[[ 4  5  6]
 [ 4 55  9]
 [ 6  0  1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[ 66,  81,  96],
        [287, 355, 423],
        [ 13,  20,  27]])

In [126]:
# Matrix multiplication element wise
print(m1)
print(m2)
mul_mat=np.multiply(m1,m2)
mul_mat

[[ 4  5  6]
 [ 4 55  9]
 [ 6  0  1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix([[  4,  10,  18],
        [ 16, 275,  54],
        [ 42,   0,   9]])

# Matrix Division

    numpy.divide(matrix_1,matrix_2)



In [127]:
print(m1)
print(m2)
div_mat=np.divide(m2,m1)
div_mat

[[ 4  5  6]
 [ 4 55  9]
 [ 6  0  1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


<ipython-input-127-98bf93b40df9>:3: RuntimeWarning: divide by zero encountered in true_divide
  div_mat=np.divide(m2,m1)


matrix([[0.25      , 0.4       , 0.5       ],
        [1.        , 0.09090909, 0.66666667],
        [1.16666667,        inf, 9.        ]])

# Linear Algeabra : numpy.linalg
Determinent of Matrix

In [128]:
print(m1)

[[ 4  5  6]
 [ 4 55  9]
 [ 6  0  1]]


In [130]:
det_mat=np.linalg.det(m1)
det_mat

-1510.0000000000002

Rank of Matrix

In [131]:
rank_m1=np.linalg.matrix_rank(m1)
print(rank_m1)

3


Inverse of Matrix

In [132]:
inv_m1=np.linalg.inv(m1)
inv_m1
# Inverse possible if matrix is non singular(Determinent Non-Zero)


matrix([[-0.03642384,  0.00331126,  0.18874172],
        [-0.03311258,  0.02119205,  0.00794702],
        [ 0.21854305, -0.01986755, -0.13245033]])